Interoperability with USD and MJCF
gazebosim/sdf_tutorials pull request #79
Opened 2022-08-18 08:44 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 New feature

## Summary

 - Remove USD install instructions
 - Remove USD tutorial
 - Created a new tutorials with link to USD and MJCF install instructions and tutorials

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-08-18 08:47 UTC, ahcorde commented
USD links are broken until this PR is merged https://github.com/gazebosim/gz-usd/pull/11

2022-08-18 19:01 UTC, azeey requested changes

2022-08-18 19:01 UTC, azeey commented on manifest.xml
> +      <markdown version='12'>interoperability_formats/tutorial.md</markdown>
MJCF is only available with version 13 and later. Maybe we should mention that in the tutorial.

2022-09-05 08:38 UTC, ahcorde commented
friendly ping @azeey

2022-09-10 00:10 UTC, azeey approved these changes

2022-09-12 07:55 UTC, merged